version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '8998:5432'
    volumes:
      - my-db:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    ports:
      - '5774:8080'
volumes:
  my-db:
